/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SW1.h
**     Project     : Mouse
**     Processor   : MKL25Z128VLK4
**     Component   : Switch
**     Version     : Component 01.007, Driver 01.08, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-11-23, 14:17, # CodeGen: 4
**     Abstract    :
**          This bean provide service of user switch devices.
**          The returned value 'TRUE' correspond to '1-2' pins 
**          connected ('ON' state of the switch). The value 'FALSE' 
**          correspond to '2-3' pins connected ('OFF' state of the switch).
**     Settings    :
**          Switch SW1 is connected to PTA20/RESET_b pin
**     Contents    :
**         GetVal     - bool SW1_GetVal(void);
**         ConnectPin - void SW1_ConnectPin(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SW1.h
** @version 01.08
** @brief
**          This bean provide service of user switch devices.
**          The returned value 'TRUE' correspond to '1-2' pins 
**          connected ('ON' state of the switch). The value 'FALSE' 
**          correspond to '2-3' pins connected ('OFF' state of the switch).
*/         
/*!
**  @addtogroup SW1_module SW1 module documentation
**  @{
*/         

#ifndef __SW1
#define __SW1

/* MODULE SW1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */
#include "Inhr1.h"

#include "Cpu.h"




bool SW1_GetVal(void);

/*
** ===================================================================
**     Method      :  SW1_GetVal (component Switch)
**     Description :
**         Return actual status of the switch
**     Parameters  : None
**     Returns     :
**         ---             - Current switch status
**                           TRUE  - '2-3' pins are connected (or the
**                           button is pressed)
**                           FALSE - '1-2' pins are connected (or the
**                           button is released)
** ===================================================================
*/

#define SW1_ConnectPin Inhr1_ConnectPin
/*
** ===================================================================
**     Method      :  SW1_ConnectPin (component Switch)
**     Description :
**         This method reconnects selected pin in this bean. This
**         method is available only for CPU derivatives and
**         peripherals that support runtime pin sharing with other
**         internal on-chip peripherals.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END SW1. */

#endif /* ifndef __SW1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
