/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Tx2.c
**     Project     : microProject
**     Processor   : MKL25Z128VLK4
**     Component   : RingBuffer
**     Version     : Component 01.029, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-12-03, 09:21, # CodeGen: 1
**     Abstract    :
**         This component implements a ring buffer for different integer data type.
**     Settings    :
**          Component name                                 : Tx2
**          Buffer Size                                    : 4
**     Contents    :
**         Clear           - void Tx2_Clear(void);
**         Put             - byte Tx2_Put(Tx2_ElementType elem);
**         Get             - byte Tx2_Get(Tx2_ElementType *elemP);
**         NofElements     - Tx2_BufSizeType Tx2_NofElements(void);
**         NofFreeElements - Tx2_BufSizeType Tx2_NofFreeElements(void);
**         Init            - void Tx2_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2014, all rights reserved.
**     Web: http://www.mcuoneclipse.com
**     This an open source software of an embedded component for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Tx2.c
** @version 01.00
** @brief
**         This component implements a ring buffer for different integer data type.
*/         
/*!
**  @addtogroup Tx2_module Tx2 module documentation
**  @{
*/         

/* MODULE Tx2. */

#include "Tx2.h"

#if Tx2_IS_REENTRANT
  #define Tx2_DEFINE_CRITICAL() CS1_CriticalVariable()
  #define Tx2_ENTER_CRITICAL()  CS1_EnterCritical()
  #define Tx2_EXIT_CRITICAL()   CS1_ExitCritical()
#else
  #define Tx2_DEFINE_CRITICAL() /* nothing */
  #define Tx2_ENTER_CRITICAL()  /* nothing */
  #define Tx2_EXIT_CRITICAL()   /* nothing */
#endif
static Tx2_ElementType Tx2_buffer[Tx2_BUF_SIZE]; /* ring buffer */
static Tx2_BufSizeType Tx2_inIdx;  /* input index */
static Tx2_BufSizeType Tx2_outIdx; /* output index */
static Tx2_BufSizeType Tx2_inSize; /* size data in buffer */
/*
** ===================================================================
**     Method      :  Tx2_Put (component RingBuffer)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte Tx2_Put(Tx2_ElementType elem)
{
  byte res = ERR_OK;
  Tx2_DEFINE_CRITICAL();

  Tx2_ENTER_CRITICAL();
  if (Tx2_inSize==Tx2_BUF_SIZE) {
    res = ERR_TXFULL;
  } else {
    Tx2_buffer[Tx2_inIdx] = elem;
    Tx2_inSize++;
    Tx2_inIdx++;
    if (Tx2_inIdx==Tx2_BUF_SIZE) {
      Tx2_inIdx = 0;
    }
  }
  Tx2_EXIT_CRITICAL();
  return res;
}

/*
** ===================================================================
**     Method      :  Tx2_Get (component RingBuffer)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte Tx2_Get(Tx2_ElementType *elemP)
{
  byte res = ERR_OK;
  Tx2_DEFINE_CRITICAL();

  Tx2_ENTER_CRITICAL();
  if (Tx2_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    *elemP = Tx2_buffer[Tx2_outIdx];
    Tx2_inSize--;
    Tx2_outIdx++;
    if (Tx2_outIdx==Tx2_BUF_SIZE) {
      Tx2_outIdx = 0;
    }
  }
  Tx2_EXIT_CRITICAL();
  return res;
}

/*
** ===================================================================
**     Method      :  Tx2_NofElements (component RingBuffer)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
Tx2_BufSizeType Tx2_NofElements(void)
{
  return Tx2_inSize;
}

/*
** ===================================================================
**     Method      :  Tx2_NofFreeElements (component RingBuffer)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
Tx2_BufSizeType Tx2_NofFreeElements(void)
{
  return (Tx2_BufSizeType)(Tx2_BUF_SIZE-Tx2_inSize);
}

/*
** ===================================================================
**     Method      :  Tx2_Init (component RingBuffer)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Tx2_Init(void)
{
  Tx2_inIdx = 0;
  Tx2_outIdx = 0;
  Tx2_inSize = 0;
}

/*
** ===================================================================
**     Method      :  Tx2_Clear (component RingBuffer)
**     Description :
**         Clear (empty) the ring buffer.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Tx2_Clear(void)
{
  Tx2_DEFINE_CRITICAL();

  Tx2_ENTER_CRITICAL();
  Tx2_Init();
  Tx2_EXIT_CRITICAL();
}

/* END Tx2. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
